[fix] fix UT for testshell after applying SSDAPILibrary
Kanaish/SSDTestShell pull request #52
Opened 2024-07-11 23:52 UTC by jiyeon-08

SSDAPILibrary 생성으로 mock이 불리지 않아 test fail하던 TC를 pass 되도록 수정하였습니다. 
리뷰 부탁드립니다!

2024-07-11 23:54 UTC, Kanaish requested changes

2024-07-11 23:54 UTC, Kanaish commented on TestShellTest/TestShellTest.cpp
> +public:
cpplint 로 space 가 없다고 검출되네요 ㅠ

2024-07-11 23:54 UTC, Kanaish commented on TestShellTest/TestShellTest.cpp
> +public:
cpplint 로 space 가 없다고 검출되네요 ㅠ

2024-07-11 23:54 UTC, Kanaish commented on TestShellTest/TestShellTest.cpp
> +protected:
cpplint 로 space 가 없다고 검출되네요 ㅠ

2024-07-12 00:00 UTC, jiyeon-08 commented on TestShellTest/TestShellTest.cpp
> +public:
수정했습니다!

2024-07-12 00:00 UTC, jiyeon-08 commented on TestShellTest/TestShellTest.cpp
> +protected:
수정했습니다!

2024-07-12 00:01 UTC, Kanaish approved these changes
깔끔한 정리 감사합니다~

2024-07-12 00:01 UTC, merged